export const ADD_TRANSCRIPTION = 'ADD_TRANSCRIPTION';
export const REMOVE_TRANSCRIPTION = 'REMOVE_TRANSCRIPTION';
export const FETCH_DATA_SUCCESS = 'FETCH_DATA_SUCCESS';
export const UPLOAD_DATA_SUCCESS = 'UPLOAD_DATA_SUCCESS';
